<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Trevor Sullivan">
<meta name="dcterms.date" content="2026-05-17">

<title>Poisson Regression and Maximum Likelihood Estimation – Trevor’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f8875d2965223058efa6f79d6d895f74.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Trevor’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> <i class="bi bi-file-earmark-check" role="img">
</i> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> <i class="bi bi-collection" role="img">
</i> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#exploring-the-data" id="toc-exploring-the-data" class="nav-link" data-scroll-target="#exploring-the-data">Exploring the Data</a>
  <ul class="collapse">
  <li><a href="#patent-counts" id="toc-patent-counts" class="nav-link" data-scroll-target="#patent-counts">Patent Counts</a></li>
  <li><a href="#regional-distribution" id="toc-regional-distribution" class="nav-link" data-scroll-target="#regional-distribution">Regional Distribution</a></li>
  <li><a href="#firm-age" id="toc-firm-age" class="nav-link" data-scroll-target="#firm-age">Firm Age</a></li>
  </ul></li>
  <li><a href="#a-simple-poisson-model-via-maximum-likelihood" id="toc-a-simple-poisson-model-via-maximum-likelihood" class="nav-link" data-scroll-target="#a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</a>
  <ul class="collapse">
  <li><a href="#why-poisson" id="toc-why-poisson" class="nav-link" data-scroll-target="#why-poisson">Why Poisson?</a></li>
  <li><a href="#the-likelihood-and-log-likelihood" id="toc-the-likelihood-and-log-likelihood" class="nav-link" data-scroll-target="#the-likelihood-and-log-likelihood">The Likelihood and Log-Likelihood</a></li>
  <li><a href="#coding-the-log-likelihood" id="toc-coding-the-log-likelihood" class="nav-link" data-scroll-target="#coding-the-log-likelihood">Coding the Log-Likelihood</a></li>
  <li><a href="#visualizing-the-log-likelihood" id="toc-visualizing-the-log-likelihood" class="nav-link" data-scroll-target="#visualizing-the-log-likelihood">Visualizing the Log-Likelihood</a></li>
  <li><a href="#the-analytical-mle" id="toc-the-analytical-mle" class="nav-link" data-scroll-target="#the-analytical-mle">The Analytical MLE</a></li>
  <li><a href="#numerical-mle" id="toc-numerical-mle" class="nav-link" data-scroll-target="#numerical-mle">Numerical MLE</a></li>
  </ul></li>
  <li><a href="#poisson-regression" id="toc-poisson-regression" class="nav-link" data-scroll-target="#poisson-regression">Poisson Regression</a>
  <ul class="collapse">
  <li><a href="#extending-the-model" id="toc-extending-the-model" class="nav-link" data-scroll-target="#extending-the-model">Extending the Model</a></li>
  <li><a href="#the-regression-log-likelihood" id="toc-the-regression-log-likelihood" class="nav-link" data-scroll-target="#the-regression-log-likelihood">The Regression Log-Likelihood</a></li>
  <li><a href="#building-the-design-matrix" id="toc-building-the-design-matrix" class="nav-link" data-scroll-target="#building-the-design-matrix">Building the Design Matrix</a></li>
  <li><a href="#finding-the-mle-and-standard-errors" id="toc-finding-the-mle-and-standard-errors" class="nav-link" data-scroll-target="#finding-the-mle-and-standard-errors">Finding the MLE and Standard Errors</a></li>
  <li><a href="#checking-against-statsmodels-glm" id="toc-checking-against-statsmodels-glm" class="nav-link" data-scroll-target="#checking-against-statsmodels-glm">Checking Against Statsmodels GLM</a></li>
  </ul></li>
  <li><a href="#the-effect-of-blueprintys-software" id="toc-the-effect-of-blueprintys-software" class="nav-link" data-scroll-target="#the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</a>
  <ul class="collapse">
  <li><a href="#from-a-coefficient-to-a-concrete-answer" id="toc-from-a-coefficient-to-a-concrete-answer" class="nav-link" data-scroll-target="#from-a-coefficient-to-a-concrete-answer">From a Coefficient to a Concrete Answer</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul></li>
  <li><a href="#appendix-model-diagnostics-and-extensions" id="toc-appendix-model-diagnostics-and-extensions" class="nav-link" data-scroll-target="#appendix-model-diagnostics-and-extensions">Appendix: Model Diagnostics and Extensions</a>
  <ul class="collapse">
  <li><a href="#fisher-information-and-the-source-of-standard-errors" id="toc-fisher-information-and-the-source-of-standard-errors" class="nav-link" data-scroll-target="#fisher-information-and-the-source-of-standard-errors">Fisher Information and the Source of Standard Errors</a></li>
  <li><a href="#does-the-poisson-distribution-actually-fit" id="toc-does-the-poisson-distribution-actually-fit" class="nav-link" data-scroll-target="#does-the-poisson-distribution-actually-fit">Does the Poisson Distribution Actually Fit?</a></li>
  <li><a href="#visualizing-the-log-likelihood-surface" id="toc-visualizing-the-log-likelihood-surface" class="nav-link" data-scroll-target="#visualizing-the-log-likelihood-surface">Visualizing the Log-Likelihood Surface</a></li>
  <li><a href="#a-confidence-interval-on-the-average-treatment-effect" id="toc-a-confidence-interval-on-the-average-treatment-effect" class="nav-link" data-scroll-target="#a-confidence-interval-on-the-average-treatment-effect">A Confidence Interval on the Average Treatment Effect</a></li>
  <li><a href="#methodological-limitations" id="toc-methodological-limitations" class="nav-link" data-scroll-target="#methodological-limitations">Methodological Limitations</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Poisson Regression and Maximum Likelihood Estimation</h1>
<p class="subtitle lead">A Case Study of Blueprinty’s Software and Patent Awards</p>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Trevor Sullivan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Blueprinty is a small software company whose flagship product helps engineering firms prepare patent-application blueprints formatted specifically for submission to the United States Patent and Trademark Office. The company’s marketing team wants to make a compelling, data-backed claim: firms that use Blueprinty’s software enjoy higher patent-approval rates.</p>
<p>The gold standard for measuring that effect would be a before-and-after study, in other words, tracking each firm’s patent success rate in the years <em>before</em> adopting the software and again <em>after</em>. No such longitudinal data exists. Instead, Blueprinty has a dataset of 1,500 mature (non-startup) engineering firms, including the following for each: the total number of patents awarded over the last five years, the firm’s geographic region, its age since incorporation, and whether it currently uses Blueprinty’s software.</p>
<p>Working with observational, cross-sectional data makes causal inference very difficult. Blueprinty’s customers are not a random subset of engineering firms, they are firms that <em>chose</em> to invest in specialized patent software. That choice is almost certainly correlated with other attributes of the firm. Older, more professionally managed companies may independently be both more likely to adopt Blueprinty <em>and</em> more likely to win patents. Firms concentrated in technology-dense regions may demonstrate the same pattern. If we just compare the average number of patents between Blueprinty users and non-users we risk attributing to the software what is really a reflection of pre-existing firm quality. Poisson regression, fitted through maximum likelihood estimation, allows to us keep age and region constant and isolate the software’s effect on patent success.</p>
</section>
<section id="exploring-the-data" class="level2">
<h2 class="anchored" data-anchor-id="exploring-the-data">Exploring the Data</h2>
<div id="cfaf20a5" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load in dataset</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data/blueprinty.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"iscustomer"</span>] <span class="op">=</span> df[<span class="st">"iscustomer"</span>].astype(<span class="bu">int</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age2"</span>] <span class="op">=</span> df[<span class="st">"age"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"customer_label"</span>] <span class="op">=</span> df[<span class="st">"iscustomer"</span>].<span class="bu">map</span>({<span class="dv">1</span>: <span class="st">"Blueprinty customers"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                                              <span class="dv">0</span>: <span class="st">"Non-customers"</span>})</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">"patents"</span>].values.astype(<span class="bu">float</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="patent-counts" class="level3">
<h3 class="anchored" data-anchor-id="patent-counts">Patent Counts</h3>
<div id="cell-fig-patents" class="cell" data-fig-height="4" data-fig-width="10" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-patents" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-patents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hw3_questions_files/figure-html/fig-patents-output-1.png" width="944" height="392" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-patents-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Five-year patent counts for non-customers (left) and Blueprinty customers (right). Both panels share the same horizontal scale.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Blueprinty customers earn more patents on average than non-customers, and the gap is visually noticeable even before any modeling. Both distributions are right-skewed with a long upper tail, which is why using a Normal distribution is a poor choice for a model. Although the difference in means is apparent, it is not on its own evidence that Blueprinty’s software is responsible: if customers are systematically older or clustered in patent-productive regions, the raw gap could reflect those differences rather than the software.</p>
</div>
</div>
</section>
<section id="regional-distribution" class="level3">
<h3 class="anchored" data-anchor-id="regional-distribution">Regional Distribution</h3>
<div id="cell-fig-region" class="cell" data-fig-height="4" data-fig-width="9" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-region" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hw3_questions_files/figure-html/fig-region-output-1.png" width="848" height="367" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-region-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Share of each customer group located in each region.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>As we can see in the figure, the two groups do not share the same regional profile. Nearly 68% of Blueprinty’s customers are located in the Northeast, whereas non-customers are more uniform across all five regions — with the Northeast accounting for only about 27% of that group. Blueprinty’s customer base is heavily concentrated in a single region. This suggests that region could a confounding variable, and holding it constant is essential to the validity of any claim about the software itself.</p>
</div>
</div>
</section>
<section id="firm-age" class="level3">
<h3 class="anchored" data-anchor-id="firm-age">Firm Age</h3>
<div id="cell-fig-age" class="cell" data-fig-height="4" data-fig-width="10" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-age" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hw3_questions_files/figure-html/fig-age-output-1.png" width="944" height="392" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-age-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Age distributions for non-customers (left) and Blueprinty customers (right), plotted on the same horizontal scale.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The age distributions of the two customer groups are more similar than we expect, and much less distinct than the regional comparison from earlier. The difference in means is less than one year. The shapes are very similar too, with both groups peaking in the early-to-mid twenties and tapering off toward older firms. That said, Blueprinty’s customer base has a slightly heavier right tail, with a meaningful number of firms in the 35–48 year range that is proportionally less represented among non-customers. The practical implication is that age is a less dramatic confounder here than region: the two groups are reasonably well-matched on this dimension, and any age-driven bias in a naive comparison would be modest. Still, because age is theoretically linked to patent capacity and shows at least some distributional difference between the groups, we include both age and age-squared in the regression to detect whatever signal may be there.</p>
</div>
</div>
</section>
</section>
<section id="a-simple-poisson-model-via-maximum-likelihood" class="level2">
<h2 class="anchored" data-anchor-id="a-simple-poisson-model-via-maximum-likelihood">A Simple Poisson Model via Maximum Likelihood</h2>
<section id="why-poisson" class="level3">
<h3 class="anchored" data-anchor-id="why-poisson">Why Poisson?</h3>
<p>The outcome of interest — the number of patents each firm receives over five years — is a count: a non-negative integer with no natural upper bound. Modeling it with a Normal distribution would be problematic because of two reasons. First, the Normal is continuous and symmetric, whereas patent counts are discrete and heavily right-skewed. Second, a Normal-based model assigns positive probability to negative patent counts, which are impossible. The Poisson distribution avoids both problems: it places mass only on the non-negative integers <span class="math inline">\(\{0, 1, 2, \ldots\}\)</span> and is fully characterized by a single rate parameter <span class="math inline">\(\lambda &gt; 0\)</span> that represents both the mean and the variance. It is the natural starting point for modeling count outcomes like these.</p>
</section>
<section id="the-likelihood-and-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="the-likelihood-and-log-likelihood">The Likelihood and Log-Likelihood</h3>
<p>If each firm’s patent count <span class="math inline">\(Y_i\)</span> is an independent draw from <span class="math inline">\(\text{Poisson}(\lambda)\)</span>, the probability of observing the value <span class="math inline">\(y_i\)</span> is:</p>
<p><span class="math display">\[f(Y_i = y_i \mid \lambda) = \frac{e^{-\lambda}\,\lambda^{y_i}}{y_i!}\]</span></p>
<p>By the independence assumption, the <strong>joint likelihood</strong> over all <span class="math inline">\(n\)</span> firms is the product of the individual probabilities:</p>
<p><span class="math display">\[L(\lambda) = \prod_{i=1}^{n} \frac{e^{-\lambda}\,\lambda^{y_i}}{y_i!} = e^{-n\lambda}\,\lambda^{\sum_i y_i}\,\prod_{i=1}^n \frac{1}{y_i!}\]</span></p>
<p>The product is unwieldy to maximize directly. Taking the natural logarithm converts it to a sum — the <strong>log-likelihood</strong> — which is easier to work with and has the same maximizer:</p>
<p><span class="math display">\[\ell(\lambda) = \log L(\lambda) = \sum_{i=1}^{n}\left[-\lambda + y_i \log\lambda - \log(y_i!)\right]\]</span></p>
<p><span class="math display">\[= -n\lambda + \left(\textstyle\sum_{i=1}^n y_i\right)\log\lambda - \sum_{i=1}^n \log(y_i!)\]</span></p>
<p>The last sum is a constant with respect to <span class="math inline">\(\lambda\)</span> and drops out of the optimization.</p>
</section>
<section id="coding-the-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="coding-the-log-likelihood">Coding the Log-Likelihood</h3>
<div id="loglik-fn" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the poission log-likelihood function</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_loglikelihood(lam, Y):</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Poisson log-likelihood as a function of the scalar rate parameter λ.</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    ----------</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">    lam : float  —  rate parameter (must be &gt; 0)</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Y   : array  —  observed count outcomes</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="co">    -------</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="co">    float : log-likelihood ℓ(λ | Y)</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.<span class="bu">sum</span>(Y <span class="op">*</span> np.log(lam) <span class="op">-</span> lam <span class="op">-</span> gammaln(Y <span class="op">+</span> <span class="dv">1</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>gammaln(Y + 1)</code> computes <span class="math inline">\(\log(Y!)\)</span> in a numerically stable way that handles large counts without overflow.</p>
</div>
</div>
</section>
<section id="visualizing-the-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-log-likelihood">Visualizing the Log-Likelihood</h3>
<div id="86207560" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for each λ and compute the mean</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>lam_grid <span class="op">=</span> np.linspace(<span class="fl">1.0</span>, <span class="fl">8.5</span>, <span class="dv">600</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ll_vals  <span class="op">=</span> [poisson_loglikelihood(lam, y) <span class="cf">for</span> lam <span class="kw">in</span> lam_grid]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>y_bar    <span class="op">=</span> y.mean()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-fig-loglik" class="cell" data-fig-height="3.5" data-fig-width="7" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>lam_grid <span class="op">=</span> np.linspace(<span class="fl">1.0</span>, <span class="fl">8.5</span>, <span class="dv">600</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ll_vals  <span class="op">=</span> [poisson_loglikelihood(lam, y) <span class="cf">for</span> lam <span class="kw">in</span> lam_grid]</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>y_bar    <span class="op">=</span> y.mean()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>ll_df <span class="op">=</span> pd.DataFrame({<span class="st">"λ"</span>: lam_grid, <span class="st">"Log-likelihood ℓ(λ)"</span>: ll_vals})</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">3.5</span>))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>sns.lineplot(</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    data      <span class="op">=</span> ll_df,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    x         <span class="op">=</span> <span class="st">"λ"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    y         <span class="op">=</span> <span class="st">"Log-likelihood ℓ(λ)"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    color     <span class="op">=</span> PURPLE,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    linewidth <span class="op">=</span> <span class="fl">2.2</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    ax        <span class="op">=</span> ax,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>ax.axvline(y_bar, color<span class="op">=</span>GREEN, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">1.7</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="vs">fr"</span><span class="dv">$</span><span class="er">\</span><span class="vs">hat</span><span class="ch">{{</span><span class="er">\</span><span class="vs">lambda</span><span class="ch">}}</span><span class="vs">_</span><span class="dv">\m</span><span class="vs">athrm</span><span class="ch">{{</span><span class="vs">MLE</span><span class="ch">}}</span><span class="vs"> = </span><span class="dv">\b</span><span class="vs">ar</span><span class="ch">{{</span><span class="vs">Y</span><span class="ch">}}</span><span class="vs"> = </span><span class="sc">{</span>y_bar<span class="sc">:.3f}</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="vs">r"Rate parameter </span><span class="dv">$</span><span class="er">\</span><span class="vs">lambda</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="vs">r"Log-likelihood </span><span class="dv">$</span><span class="ch">\;</span><span class="er">\</span><span class="vs">ell</span><span class="kw">(</span><span class="er">\</span><span class="vs">lambda</span><span class="kw">)</span><span class="dv">$</span><span class="vs">"</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Poisson Log-Likelihood over Observed Patent Counts"</span>,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>             fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>sns.despine(ax<span class="op">=</span>ax)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div id="fig-loglik" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loglik-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hw3_questions_files/figure-html/fig-loglik-output-1.png" width="654" height="317" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loglik-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The Poisson log-likelihood evaluated at the observed patent counts, peaking at the sample mean.
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The curve is strictly concave. It rises steeply from the left, reaches a single peak, and then decreases more gradually to the right, and that asymmetry is worth noting. Overestimating <span class="math inline">\(\lambda\)</span> (moving right of the peak) is penalized less sharply than underestimating it (moving left), reflecting the Poisson distribution’s own right skew. The peak sits precisely at <span class="math inline">\(\hat{\lambda}_{\text{MLE}} = \bar{Y} = 3.685\)</span>, confirming that the average firm in this dataset received about 3.7 patents over the five-year window. To “read” the MLE off the plot, simply find the value of <span class="math inline">\(\lambda\)</span> on the horizontal axis directly below the highest point on the curve, and moving from 3.685 in either direction produces a strictly lower log-likelihood, meaning the data are less consistent with that rate.</p>
</div>
</div>
</section>
<section id="the-analytical-mle" class="level3">
<h3 class="anchored" data-anchor-id="the-analytical-mle">The Analytical MLE</h3>
<p>Taking the first derivative and setting it to zero:</p>
<p><span class="math display">\[\frac{d\ell}{d\lambda} = -n + \frac{\displaystyle\sum_{i=1}^n y_i}{\lambda} = 0 \quad\Longrightarrow\quad \hat\lambda_{\text{MLE}} = \frac{1}{n}\sum_{i=1}^n y_i = \bar{Y}\]</span></p>
<p>The MLE is simply the sample mean. This is intuitively satisfying: the Poisson distribution has mean <span class="math inline">\(\lambda\)</span>, so the best estimate of <span class="math inline">\(\lambda\)</span> from the data is the empirical average of the observed counts.</p>
</section>
<section id="numerical-mle" class="level3">
<h3 class="anchored" data-anchor-id="numerical-mle">Numerical MLE</h3>
<div id="simple-mle" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize_scalar</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Find MLE with scipy function</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>num_result <span class="op">=</span> minimize_scalar(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    fun    <span class="op">=</span> <span class="kw">lambda</span> lam: <span class="op">-</span>poisson_loglikelihood(lam, y),</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    bounds <span class="op">=</span> (<span class="fl">0.01</span>, <span class="fl">50.0</span>),</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    method <span class="op">=</span> <span class="st">"bounded"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>lam_hat <span class="op">=</span> num_result.x</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Numerical MLE  (scipy) : λ̂ = </span><span class="sc">{</span>lam_hat<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample mean           : ȳ  = </span><span class="sc">{</span>y<span class="sc">.</span>mean()<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Absolute difference   :    </span><span class="sc">{</span><span class="bu">abs</span>(lam_hat <span class="op">-</span> y.mean())<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Numerical MLE  (scipy) : λ̂ = 3.684666
Sample mean           : ȳ  = 3.684667
Absolute difference   :    5.83e-07</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The numerical MLE and the sample mean agree to six decimal places, differing by less than <span class="math inline">\(6 \times 10^{-7}\)</span>, which is well within the tolerance of floating-point arithmetic. This is exactly what the analytical derivation predicts: the Poisson log-likelihood has a single critical point at <span class="math inline">\(\bar{Y} = 3.684667\)</span>, so the optimizer has nowhere else to go. The tiny difference is not a modeling discrepancy; it’s just the optimizer’s convergence tolerance doing its job. This validates the fact that the <code>poisson_loglikelihood</code> function is coded correctly before we use it in the more complex regression setting later on.</p>
</div>
</div>
</section>
</section>
<section id="poisson-regression" class="level2">
<h2 class="anchored" data-anchor-id="poisson-regression">Poisson Regression</h2>
<section id="extending-the-model" class="level3">
<h3 class="anchored" data-anchor-id="extending-the-model">Extending the Model</h3>
<p>The single-<span class="math inline">\(\lambda\)</span> model assumes every firm is drawn from the same Poisson process. That model is too strict. A firm with decades of experience, an established patent department, and a team of IP attorneys is fundamentally different from a younger firm still building those capabilities. Poisson regression relaxes the assumption by letting each firm’s rate parameter depend on its own observed characteristics:</p>
<p><span class="math display">\[Y_i \sim \text{Poisson}(\lambda_i) \qquad \text{where} \qquad \lambda_i = \exp(X_i'\boldsymbol{\beta})\]</span></p>
<p>The exponential function serves as the <em>inverse link</em>. The linear predictor <span class="math inline">\(X_i'\boldsymbol{\beta}\)</span> can take any real value, but <span class="math inline">\(\lambda_i = \exp(X_i'\boldsymbol{\beta})\)</span> is always strictly positive, which is exactly what we require for a Poisson rate. The model is now a function of a coefficient vector <span class="math inline">\(\boldsymbol{\beta}\)</span> that we need to estimate from the data.</p>
</section>
<section id="the-regression-log-likelihood" class="level3">
<h3 class="anchored" data-anchor-id="the-regression-log-likelihood">The Regression Log-Likelihood</h3>
<p>The log-likelihood generalizes naturally: replace the common <span class="math inline">\(\lambda\)</span> with firm-specific <span class="math inline">\(\lambda_i = \exp(X_i'\boldsymbol{\beta})\)</span>:</p>
<p><span class="math display">\[\ell(\boldsymbol{\beta}) = \sum_{i=1}^n \Bigl[ y_i\,(X_i'\boldsymbol{\beta}) - \exp(X_i'\boldsymbol{\beta}) - \log(y_i!) \Bigr]\]</span></p>
<div id="reg-loglik-fn" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the log-likelihood function now with the coefficient vector parameter</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_regression_loglikelihood(beta, Y, X):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Poisson regression log-likelihood as a function of the coefficient vector β.</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Parameters</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">    ----------</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co">    beta : array-like, shape (p,)   —  coefficient vector</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Y    : array-like, shape (n,)   —  observed count outcomes</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">    X    : ndarray,    shape (n, p) —  design matrix (intercept in column 0)</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">    -------</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co">    float : log-likelihood value ℓ(β | Y, X)</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(X <span class="op">@</span> beta)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.<span class="bu">sum</span>(Y <span class="op">*</span> np.log(lam) <span class="op">-</span> lam <span class="op">-</span> gammaln(Y <span class="op">+</span> <span class="dv">1</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="building-the-design-matrix" class="level3">
<h3 class="anchored" data-anchor-id="building-the-design-matrix">Building the Design Matrix</h3>
<div id="design-matrix" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize age for numerical stability before squaring</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>age_mean <span class="op">=</span> df[<span class="st">"age"</span>].mean()</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>age_std  <span class="op">=</span> df[<span class="st">"age"</span>].std()</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age_s"</span>]  <span class="op">=</span> (df[<span class="st">"age"</span>] <span class="op">-</span> age_mean) <span class="op">/</span> age_std</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>df[<span class="st">"age2_s"</span>] <span class="op">=</span> df[<span class="st">"age_s"</span>] <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop first alphabetical region as baseline</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>region_dummies <span class="op">=</span> pd.get_dummies(df[<span class="st">"region"</span>], drop_first<span class="op">=</span><span class="va">True</span>).astype(<span class="bu">float</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>ref_region     <span class="op">=</span> <span class="bu">sorted</span>(df[<span class="st">"region"</span>].unique())[<span class="dv">0</span>]</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>X_df <span class="op">=</span> pd.concat([</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    pd.Series(np.ones(<span class="bu">len</span>(df)), name<span class="op">=</span><span class="st">"intercept"</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"age_s"</span>, <span class="st">"age2_s"</span>]].astype(<span class="bu">float</span>),</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    region_dummies,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    df[[<span class="st">"iscustomer"</span>]].astype(<span class="bu">float</span>),</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>], axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>X_reg <span class="op">=</span> X_df.values</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Design matrix columns:"</span>, <span class="bu">list</span>(X_df.columns))</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape:"</span>, X_reg.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Design matrix columns: ['intercept', 'age_s', 'age2_s', 'Northeast', 'Northwest', 'South', 'Southwest', 'iscustomer']
Shape: (1500, 8)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Explanation
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Age squared:</strong> the relationship between firm age and patent output is unlikely to be perfectly linear. A young firm may grow its patent capacity quickly as it matures, while a very old firm may plateau or slow down. Including <code>age²</code> alongside <code>age</code> lets the model capture this nonlinearity. <strong>Dropping one region:</strong> if we included a dummy for every region plus an intercept, one column would be perfectly predictable as a linear combination of the others, making the design matrix singular and the MLE undefined. Dropping one region (here, the first alphabetically) sets it as the baseline category, which means that the remaining region coefficients are interpreted relative to that baseline.</p>
</div>
</div>
</section>
<section id="finding-the-mle-and-standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="finding-the-mle-and-standard-errors">Finding the MLE and Standard Errors</h3>
<p>We minimize the negative log-likelihood with <code>scipy</code>’s BFGS optimizer, then recover standard errors from the <strong>Fisher information matrix</strong>. At the MLE, the Poisson Fisher information is <span class="math inline">\(\mathbf{I}(\hat{\boldsymbol\beta}) = X^\top \hat{W} X\)</span>, where <span class="math inline">\(\hat{W} = \operatorname{diag}(\hat\lambda_1, \ldots, \hat\lambda_n)\)</span>. The asymptotic covariance matrix is <span class="math inline">\(\mathbf{I}(\hat{\boldsymbol\beta})^{-1}\)</span>, and the standard errors are the square roots of its diagonal entries.</p>
<div id="reg-mle" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> neg_loglik_reg(beta):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(X_reg <span class="op">@</span> beta)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span><span class="bu">float</span>(np.<span class="bu">sum</span>(y <span class="op">*</span> np.log(lam) <span class="op">-</span> lam <span class="op">-</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>)))</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> grad_neg_loglik(beta):</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.exp(X_reg <span class="op">@</span> beta)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="op">-</span>(X_reg.T <span class="op">@</span> (y <span class="op">-</span> lam))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>result_reg <span class="op">=</span> minimize(</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    neg_loglik_reg,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    x0      <span class="op">=</span> np.zeros(X_reg.shape[<span class="dv">1</span>]),</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    jac     <span class="op">=</span> grad_neg_loglik,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    method  <span class="op">=</span> <span class="st">"L-BFGS-B"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    options <span class="op">=</span> {<span class="st">"maxiter"</span>: <span class="dv">10000</span>, <span class="st">"ftol"</span>: <span class="fl">2.2e-15</span>, <span class="st">"gtol"</span>: <span class="fl">1e-8</span>},</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>beta_mle <span class="op">=</span> result_reg.x</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>lam_hat <span class="op">=</span> np.exp(X_reg <span class="op">@</span> beta_mle)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>FIM     <span class="op">=</span> (X_reg <span class="op">*</span> lam_hat[:, np.newaxis]).T <span class="op">@</span> X_reg   <span class="co"># efficient X'WX</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>cov_mle <span class="op">=</span> np.linalg.inv(FIM)</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>se_mle  <span class="op">=</span> np.sqrt(np.diag(cov_mle))</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Optimization converged : </span><span class="sc">{</span>result_reg<span class="sc">.</span>success<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Final log-likelihood   : </span><span class="sc">{</span><span class="op">-</span>result_reg<span class="sc">.</span>fun<span class="sc">:,.2f}</span><span class="ss">"</span>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'Term'</span><span class="sc">:&lt;28}</span><span class="ss">  </span><span class="sc">{</span><span class="st">'β̂'</span><span class="sc">:&gt;9}</span><span class="ss">  </span><span class="sc">{</span><span class="st">'SE'</span><span class="sc">:&gt;9}</span><span class="ss">"</span>)</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"-"</span> <span class="op">*</span> <span class="dv">50</span>)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, b, se <span class="kw">in</span> <span class="bu">zip</span>(X_df.columns, beta_mle, se_mle):</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;28}</span><span class="ss">  </span><span class="sc">{</span>b<span class="sc">:&gt;9.4f}</span><span class="ss">  </span><span class="sc">{</span>se<span class="sc">:&gt;9.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization converged : True
Final log-likelihood   : -3,258.07

Term                                 β̂         SE
--------------------------------------------------
intercept                        1.3447     0.0384
age_s                           -0.0577     0.0150
age2_s                          -0.1558     0.0135
Northeast                        0.0292     0.0436
Northwest                       -0.0176     0.0538
South                            0.0566     0.0527
Southwest                        0.0506     0.0472
iscustomer                       0.2076     0.0309</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Explanation
</div>
</div>
<div class="callout-body-container callout-body">
<p>We return a final log-likelihood of −3,258.07. All standard errors are well-defined and of sensible magnitude — the largest belong to the intercept and region indicators, and the smallest to <code>iscustomer</code>, which is estimated precisely despite being a binary variable. The <code>iscustomer</code> coefficient of 0.2076 (SE = 0.0309) is already clearly distinguishable from zero, but before interpreting it we verify the result against <code>statsmodels</code> as a cross-check.</p>
</div>
</div>
</section>
<section id="checking-against-statsmodels-glm" class="level3">
<h3 class="anchored" data-anchor-id="checking-against-statsmodels-glm">Checking Against Statsmodels GLM</h3>
<div id="glm-fit" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit statsmodels GLM</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>glm_result <span class="op">=</span> sm.GLM(</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    endog  <span class="op">=</span> df[<span class="st">"patents"</span>],</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    exog   <span class="op">=</span> X_df,</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    family <span class="op">=</span> sm.families.Poisson(),</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>).fit()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-execution_count="14">
<div id="tbl-coefficients" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="14">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-coefficients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-coefficients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="34">
<div id="asfvavuipz" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>
#asfvavuipz table {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
        }

#asfvavuipz thead, tbody, tfoot, tr, td, th { border-style: none; }
 tr { background-color: transparent; }
#asfvavuipz p { margin: 0; padding: 0; }
 #asfvavuipz .gt_table { display: table; border-collapse: collapse; line-height: normal; margin-left: auto; margin-right: auto; color: #333333; font-size: 16px; font-weight: normal; font-style: normal; background-color: #FFFFFF; width: auto; border-top-style: solid; border-top-width: 2px; border-top-color: #A8A8A8; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #A8A8A8; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; }
 #asfvavuipz .gt_caption { padding-top: 4px; padding-bottom: 4px; }
 #asfvavuipz .gt_title { color: #333333; font-size: 125%; font-weight: initial; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; border-bottom-color: #FFFFFF; border-bottom-width: 0; }
 #asfvavuipz .gt_subtitle { color: #333333; font-size: 85%; font-weight: initial; padding-top: 3px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; border-top-color: #FFFFFF; border-top-width: 0; }
 #asfvavuipz .gt_heading { background-color: #FFFFFF; text-align: center; border-bottom-color: #FFFFFF; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }
 #asfvavuipz .gt_bottom_border { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }
 #asfvavuipz .gt_col_headings { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; }
 #asfvavuipz .gt_col_heading { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; padding-left: 5px; padding-right: 5px; overflow-x: hidden; }
 #asfvavuipz .gt_column_spanner_outer { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: normal; text-transform: inherit; padding-top: 0; padding-bottom: 0; padding-left: 4px; padding-right: 4px; }
 #asfvavuipz .gt_column_spanner_outer:first-child { padding-left: 0; }
 #asfvavuipz .gt_column_spanner_outer:last-child { padding-right: 0; }
 #asfvavuipz .gt_column_spanner { border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: bottom; padding-top: 5px; padding-bottom: 5px; overflow-x: hidden; display: inline-block; width: 100%; }
 #asfvavuipz .gt_spanner_row { border-bottom-style: hidden; }
 #asfvavuipz .gt_group_heading { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; text-align: left; }
 #asfvavuipz .gt_empty_group_heading { padding: 0.5px; color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; vertical-align: middle; }
 #asfvavuipz .gt_from_md> :first-child { margin-top: 0; }
 #asfvavuipz .gt_from_md> :last-child { margin-bottom: 0; }
 #asfvavuipz .gt_row { padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; margin: 10px; border-top-style: solid; border-top-width: 1px; border-top-color: #D3D3D3; border-left-style: none; border-left-width: 1px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 1px; border-right-color: #D3D3D3; vertical-align: middle; overflow-x: hidden; }
 #asfvavuipz .gt_stub { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; }
 #asfvavuipz .gt_stub_row_group { color: #333333; background-color: #FFFFFF; font-size: 100%; font-weight: initial; text-transform: inherit; border-right-style: solid; border-right-width: 2px; border-right-color: #D3D3D3; padding-left: 5px; padding-right: 5px; vertical-align: top; }
 #asfvavuipz .gt_row_group_first td { border-top-width: 2px; }
 #asfvavuipz .gt_row_group_first th { border-top-width: 2px; }
 #asfvavuipz .gt_striped { color: #333333; background-color: #F4F4F4; }
 #asfvavuipz .gt_table_body { border-top-style: solid; border-top-width: 2px; border-top-color: #D3D3D3; border-bottom-style: solid; border-bottom-width: 2px; border-bottom-color: #D3D3D3; }
 #asfvavuipz .gt_grand_summary_row { color: #333333; background-color: #FFFFFF; text-transform: inherit; padding-top: 8px; padding-bottom: 8px; padding-left: 5px; padding-right: 5px; }
 #asfvavuipz .gt_first_grand_summary_row_bottom { border-top-style: double; border-top-width: 6px; border-top-color: #D3D3D3; }
 #asfvavuipz .gt_last_grand_summary_row_top { border-bottom-style: double; border-bottom-width: 6px; border-bottom-color: #D3D3D3; }
 #asfvavuipz .gt_sourcenotes { color: #333333; background-color: #FFFFFF; border-bottom-style: none; border-bottom-width: 2px; border-bottom-color: #D3D3D3; border-left-style: none; border-left-width: 2px; border-left-color: #D3D3D3; border-right-style: none; border-right-width: 2px; border-right-color: #D3D3D3; }
 #asfvavuipz .gt_sourcenote { font-size: 90%; padding-top: 4px; padding-bottom: 4px; padding-left: 5px; padding-right: 5px; text-align: left; }
 #asfvavuipz .gt_left { text-align: left; }
 #asfvavuipz .gt_center { text-align: center; }
 #asfvavuipz .gt_right { text-align: right; font-variant-numeric: tabular-nums; }
 #asfvavuipz .gt_font_normal { font-weight: normal; }
 #asfvavuipz .gt_font_bold { font-weight: bold; }
 #asfvavuipz .gt_font_italic { font-style: italic; }
 #asfvavuipz .gt_super { font-size: 65%; }
 #asfvavuipz .gt_footnote_marks { font-size: 75%; vertical-align: 0.4em; position: initial; }
 #asfvavuipz .gt_asterisk { font-size: 100%; vertical-align: 0; }
 
</style>

<table class="gt_table do-not-create-environment caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<thead>
<tr class="gt_heading header">
<td colspan="8" class="gt_heading gt_title gt_font_normal" style="color: #9158A2; font-weight: bold">Poisson Regression Coefficient Estimates</td>
</tr>
<tr class="gt_heading even">
<td colspan="8" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border">Outcome: five-year patent count | n = 1,500 | Reference region: Midwest</td>
</tr>
<tr class="gt_col_headings gt_spanner_row header">
<th rowspan="2" id="Term" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">Term</th>
<th colspan="2" id="Point-Estimate" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="colgroup"><span class="gt_column_spanner">Point Estimate</span></th>
<th rowspan="2" id="Std.-Error" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">Std. Error</th>
<th rowspan="2" id="z" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">z</th>
<th rowspan="2" id="p-value" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">p-value</th>
<th colspan="2" id="95%-Confidence-Interval" class="gt_center gt_columns_top_border gt_column_spanner_outer" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="colgroup"><span class="gt_column_spanner">95% Confidence Interval</span></th>
</tr>
<tr class="gt_col_headings even">
<th id="scipy-β̂" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">scipy β̂</th>
<th id="GLM-β̂" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">GLM β̂</th>
<th id="CI-Low" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">CI Low</th>
<th id="CI-High" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" style="color: #9158A2; font-weight: bold" scope="col">CI High</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left">Intercept</td>
<td class="gt_row gt_right">1.3447</td>
<td class="gt_row gt_right">1.3447</td>
<td class="gt_row gt_right">0.0384</td>
<td class="gt_row gt_right">35.0587</td>
<td class="gt_row gt_right">2.87 × 10<sup>−269</sup></td>
<td class="gt_row gt_right">1.2695</td>
<td class="gt_row gt_right">1.4199</td>
</tr>
<tr class="even">
<td class="gt_row gt_left">Firm age (std.)</td>
<td class="gt_row gt_right">−0.0577</td>
<td class="gt_row gt_right">−0.0577</td>
<td class="gt_row gt_right">0.0150</td>
<td class="gt_row gt_right">−3.8431</td>
<td class="gt_row gt_right">1.21 × 10<sup>−4</sup></td>
<td class="gt_row gt_right">−0.0872</td>
<td class="gt_row gt_right">−0.0283</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left">Firm age² (std.)</td>
<td class="gt_row gt_right">−0.1558</td>
<td class="gt_row gt_right">−0.1558</td>
<td class="gt_row gt_right">0.0135</td>
<td class="gt_row gt_right">−11.5132</td>
<td class="gt_row gt_right">1.13 × 10<sup>−30</sup></td>
<td class="gt_row gt_right">−0.1823</td>
<td class="gt_row gt_right">−0.1293</td>
</tr>
<tr class="even">
<td class="gt_row gt_left">Region: Northeast</td>
<td class="gt_row gt_right">0.0292</td>
<td class="gt_row gt_right">0.0292</td>
<td class="gt_row gt_right">0.0436</td>
<td class="gt_row gt_right">0.6686</td>
<td class="gt_row gt_right">5.04 × 10<sup>−1</sup></td>
<td class="gt_row gt_right">−0.0563</td>
<td class="gt_row gt_right">0.1147</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left">Region: Northwest</td>
<td class="gt_row gt_right">−0.0176</td>
<td class="gt_row gt_right">−0.0176</td>
<td class="gt_row gt_right">0.0538</td>
<td class="gt_row gt_right">−0.3268</td>
<td class="gt_row gt_right">7.44 × 10<sup>−1</sup></td>
<td class="gt_row gt_right">−0.1230</td>
<td class="gt_row gt_right">0.0878</td>
</tr>
<tr class="even">
<td class="gt_row gt_left">Region: South</td>
<td class="gt_row gt_right">0.0566</td>
<td class="gt_row gt_right">0.0566</td>
<td class="gt_row gt_right">0.0527</td>
<td class="gt_row gt_right">1.0740</td>
<td class="gt_row gt_right">2.83 × 10<sup>−1</sup></td>
<td class="gt_row gt_right">−0.0467</td>
<td class="gt_row gt_right">0.1598</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left">Region: Southwest</td>
<td class="gt_row gt_right">0.0506</td>
<td class="gt_row gt_right">0.0506</td>
<td class="gt_row gt_right">0.0472</td>
<td class="gt_row gt_right">1.0716</td>
<td class="gt_row gt_right">2.84 × 10<sup>−1</sup></td>
<td class="gt_row gt_right">−0.0419</td>
<td class="gt_row gt_right">0.1431</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">Blueprinty customer</td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">0.2076</td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">0.2076</td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">0.0309</td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">6.7192</td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">1.83 × 10<sup>−11</sup></td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">0.1470</td>
<td class="gt_row gt_right" style="background-color: #F3EEF6; color: #9158A2; font-weight: bold">0.2681</td>
</tr>
</tbody><tfoot class="gt_sourcenotes">
<tr class="odd">
<td colspan="8" class="gt_sourcenote">scipy: L-BFGS-B with analytical Fisher information SEs. GLM: iteratively reweighted least squares. Reference region: Midwest.</td>
</tr>
</tfoot>

</table>


</div>
</div>
</div>
</figure>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Blueprinty customer</strong> (highlighted): The estimate of 0.2076 (SE = 0.0309) is the most important number in the table. It is positive, precisely estimated, and associated with a p-value of <span class="math inline">\(1.83 \times 10^{-11}\)</span>, which is extremely small. Controlling for firm age and region, being a Blueprinty customer is associated with a <span class="math inline">\(\exp(0.2076) \approx 1.23\)</span> multiplicative increase in expected patent count, which means that customers are expected to receive about 23% more patents than an otherwise identical non-customer firm. Both confidence interval bounds (0.147, 0.268) are comfortably above zero.</p>
<p><strong>Firm age (standardized):</strong> The negative linear term (−0.0577) and negative quadratic term (−0.1558) together imply that patent output <em>declines</em> with age across the range of this sample, with the decline accelerating for older firms. This may seem counterintuitive, but it is consistent with a sample of mature firms past their most innovative years, or simply with younger cohorts being more active filers. Both terms are statistically significant.</p>
<p><strong>Region:</strong> None of the four region coefficients (relative to the Midwest baseline) is individually significant at conventional levels. All p-values exceed 0.28. This is perhaps surprising given the dramatic Northeast concentration we observed in the EDA, but it reflects the fact that once <em>customer status</em> is in the model, regional variation in patent rates is modest. The Northeast dummy is positive but small and imprecisely estimated, suggesting an interaction in the data that Northeast advantage largely operates <em>through</em> the higher number of Blueprinty customers there.</p>
</div>
</div>
</section>
</section>
<section id="the-effect-of-blueprintys-software" class="level2">
<h2 class="anchored" data-anchor-id="the-effect-of-blueprintys-software">The Effect of Blueprinty’s Software</h2>
<section id="from-a-coefficient-to-a-concrete-answer" class="level3">
<h3 class="anchored" data-anchor-id="from-a-coefficient-to-a-concrete-answer">From a Coefficient to a Concrete Answer</h3>
<p>The customer coefficient in the table is interpretable in log-multiplicative units, which is precise but not very intuitive. Blueprinty’s marketing team as well as the engineering firms evaluating the software would rather know the following question: <em>how many additional patents can we expect?</em> To answer that, we use the fitted model to run a simple thought experiment. For every firm in the dataset, we ask: what would the model predict for this firm’s patent count if it <em>were</em> a Blueprinty customer, and what would it predict if it <em>were not</em>, holding age and region constant at their actual observed values?</p>
<div id="ate" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counterfactual datasets</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>X0 <span class="op">=</span> X_df.copy()<span class="op">;</span>  X0[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="fl">0.0</span>   <span class="co"># all firms set to non-customer</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="op">=</span> X_df.copy()<span class="op">;</span>  X1[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="fl">1.0</span>   <span class="co"># all firms set to customer</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicted expected counts under each scenario</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>yhat0 <span class="op">=</span> np.exp(X0.values <span class="op">@</span> glm_result.params.values)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>yhat1 <span class="op">=</span> np.exp(X1.values <span class="op">@</span> glm_result.params.values)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Average Treatment Effect</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>ate <span class="op">=</span> <span class="bu">float</span>(np.mean(yhat1 <span class="op">-</span> yhat0))</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean predicted patents WITHOUT Blueprinty : </span><span class="sc">{</span>yhat0<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Mean predicted patents WITH Blueprinty    : </span><span class="sc">{</span>yhat1<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average Treatment Effect (ATE)            : </span><span class="sc">{</span>ate<span class="sc">:.4f}</span><span class="ss"> additional patents"</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Relative uplift                           : </span><span class="sc">{</span>ate <span class="op">/</span> yhat0<span class="sc">.</span>mean() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean predicted patents WITHOUT Blueprinty : 3.4362
Mean predicted patents WITH Blueprinty    : 4.2290
Average Treatment Effect (ATE)            : 0.7928 additional patents
Relative uplift                           : 23.1%</code></pre>
</div>
</div>
<div id="cell-fig-ate" class="cell" data-fig-height="4" data-fig-width="8" data-execution_count="16">
<div class="cell-output cell-output-display">
<div id="fig-ate" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hw3_questions_files/figure-html/fig-ate-output-1.png" width="752" height="364" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ate-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Distribution of firm-level treatment effects — the difference in predicted patent count between the Blueprinty-customer and non-customer scenarios for each firm, holding age and region fixed. The red dashed line marks the Average Treatment Effect (ATE).
</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The distribution tells a very clear story: it is not symmetric and it is not centered near zero. The mass is concentrated between 0.75 and 0.95 additional patents, with a long left tail pulling the average slightly downward. This shape is a direct consequence of the multiplicative structure of Poisson regression: the individual treatment effect for firm <span class="math inline">\(i\)</span> is <span class="math inline">\(\hat\lambda_i \cdot (\exp(\hat\beta_{\text{customer}}) - 1)\)</span>, so firms with higher baseline patent rates receive larger absolute gains. Firms in the left tail, or those predicted to receive fewer patents regardless, benefit less in absolute terms even though the <em>proportional</em> effect is identical for everyone.</p>
<p>Averaging across all 1,500 firms, the <strong>Average Treatment Effect is 0.793 additional patents over five years</strong>, which is interpreted as a 23.1% increase relative to the counterfactual non-customer baseline of 3.44 patents. To put this in business terms, the model estimates that a typical engineering firm would receive roughly three-quarters of an additional patent per five-year period by adopting Blueprinty’s software, after accounting for its age and location.</p>
</div>
</div>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>This is a very strong and statistically robust finding. The customer coefficient is precisely estimated (<span class="math inline">\(p = 1.83 \times 10^{-11}\)</span>), the confidence interval on the ATE is bounded well above zero, and the result survives the inclusion of age and regional controls that we identified as potential confounders in the exploratory analysis.</p>
<p>That said, it’s important to note what we can and cannot take away from this analysis. This is an observational study: Blueprinty’s customers chose to adopt the software, and firms that make that investment may differ from non-customers in unobserved ways that independently drive patent success, which include larger R&amp;D budgets, dedicated IP departments, and more ambitious patent strategies. Without random assignment to treatment, we cannot fully rule out such confounders. The honest claim is therefore not that Blueprinty <em>causes</em> firms to win more patents, but that firms using Blueprinty win more patents even after accounting for observable differences in age and location. For a marketing team working with observational data, that is a defensible and meaningful result.</p>
</section>
</section>
<section id="appendix-model-diagnostics-and-extensions" class="level2">
<h2 class="anchored" data-anchor-id="appendix-model-diagnostics-and-extensions">Appendix: Model Diagnostics and Extensions</h2>
<section id="fisher-information-and-the-source-of-standard-errors" class="level3">
<h3 class="anchored" data-anchor-id="fisher-information-and-the-source-of-standard-errors">Fisher Information and the Source of Standard Errors</h3>
<p>The standard errors in the regression table aren’t random outputs of the optimizer, they have a precise theoretical justification rooted in Fisher’s fundamental theorem for the MLE. For a Poisson regression model with <span class="math inline">\(n\)</span> observations and <span class="math inline">\(p\)</span> coefficients, the Fisher information matrix is</p>
<p><span class="math display">\[\mathbf{I}(\boldsymbol\beta) = X^\top W X\]</span></p>
<p>where <span class="math inline">\(W = \text{diag}(\lambda_1, \ldots, \lambda_n)\)</span> is a diagonal matrix of the fitted rates. Fisher’s result for multiparameter families states that in large samples</p>
<p><span class="math display">\[\hat{\boldsymbol\beta} \;\dot\sim\; \mathcal{N}_p\!\left(\boldsymbol\beta,\;
\mathbf{I}(\hat{\boldsymbol\beta})^{-1}\right)\]</span></p>
<p>so the asymptotic covariance matrix of the MLE is the inverse of the Fisher information evaluated at <span class="math inline">\(\hat{\boldsymbol\beta}\)</span>, and the standard errors are the square roots of its diagonal entries. This is exactly what the line <code>se_mle = sqrt(diag(inv(FIM)))</code> computes. A larger Fisher information, or a more sharply curved log-likelihood, indicates a more precisely estimated coefficient. The narrow confidence interval on the customer coefficient reflects the fact that <span class="math inline">\(\mathbf{I}(\hat{\boldsymbol\beta})\)</span> is large in the direction of <span class="math inline">\(\beta_{\text{customer}}\)</span>, i.e., the log-likelihood surface is steep around the MLE in that dimension.</p>
</section>
<section id="does-the-poisson-distribution-actually-fit" class="level3">
<h3 class="anchored" data-anchor-id="does-the-poisson-distribution-actually-fit">Does the Poisson Distribution Actually Fit?</h3>
<p>The Poisson distribution has one structural constraint: its mean and variance are equal, both equal to <span class="math inline">\(\lambda\)</span>. Real count data, especially firm-level outcomes like patent counts, often violates this, showing <em>overdispersion</em> where the variance substantially exceeds the mean. If that is the case here, the Poisson model is misspecified, and our standard errors will be underestimated, making inference anti-conservative.</p>
<p>A quick check for this is to compare the sample mean and variance of the outcome directly.</p>
<div id="overdispersion-check" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>mean_y <span class="op">=</span> y.mean()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>var_y  <span class="op">=</span> y.var()</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>ratio  <span class="op">=</span> var_y <span class="op">/</span> mean_y</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample mean        : </span><span class="sc">{</span>mean_y<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Sample variance    : </span><span class="sc">{</span>var_y<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Variance / mean    : </span><span class="sc">{</span>ratio<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if ratio indicates overdispersion</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> ratio <span class="op">&gt;</span> <span class="fl">1.5</span>:</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Substantial overdispersion detected."</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Consider quasi-Poisson or negative binomial as a robustness check."</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="cf">elif</span> ratio <span class="op">&gt;</span> <span class="fl">1.1</span>:</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Mild overdispersion. Poisson is a reasonable approximation,"</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"but standard errors may be slightly underestimated."</span>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="cf">else</span>:</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"Variance ≈ mean. Poisson mean-variance assumption is well supported."</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sample mean        : 3.6847
Sample variance    : 5.5306
Variance / mean    : 1.5010

Substantial overdispersion detected.
Consider quasi-Poisson or negative binomial as a robustness check.</code></pre>
</div>
</div>
<p>If the ratio is substantially above 1, a quasi-Poisson or negative binomial model would be more appropriate. Quasi-Poisson retains the same coefficient estimates as Poisson regression but inflates the standard errors by a dispersion factor <span class="math inline">\(\hat\phi = \text{variance}/\text{mean}\)</span>, producing more honest uncertainty estimates. A negative binomial model goes further by explicitly modeling the overdispersion as a second parameter. Either would serve as a useful robustness check, and if the customer coefficient survives with similar magnitude and significance under those specifications, the finding is more solid.</p>
</section>
<section id="visualizing-the-log-likelihood-surface" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-the-log-likelihood-surface">Visualizing the Log-Likelihood Surface</h3>
<p>The 1D log-likelihood plot shown earlier illustrates the shape of the curve for a single parameter. For the regression model, the relevant object is a surface in <span class="math inline">\(p\)</span> dimensions, which is impossible to visualize in full, but informative to slice. The contour plot below shows the log-likelihood as a function of the intercept <span class="math inline">\(\beta_0\)</span> and the customer coefficient <span class="math inline">\(\beta_{\text{customer}}\)</span>, holding all other coefficients constant at their MLE values.</p>
<div id="ec55f709" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>b0_grid    <span class="op">=</span> np.linspace(beta_mle[<span class="dv">0</span>]  <span class="op">-</span> <span class="fl">0.15</span>, beta_mle[<span class="dv">0</span>]  <span class="op">+</span> <span class="fl">0.15</span>, <span class="dv">80</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>bcust_grid <span class="op">=</span> np.linspace(beta_mle[<span class="op">-</span><span class="dv">1</span>] <span class="op">-</span> <span class="fl">0.25</span>, beta_mle[<span class="op">-</span><span class="dv">1</span>] <span class="op">+</span> <span class="fl">0.25</span>, <span class="dv">80</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>LL <span class="op">=</span> np.zeros((<span class="dv">80</span>, <span class="dv">80</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute log-likelihood for each b0 and bcust coefficient pair</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, b0 <span class="kw">in</span> <span class="bu">enumerate</span>(b0_grid):</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j, bc <span class="kw">in</span> <span class="bu">enumerate</span>(bcust_grid):</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> beta_mle.copy()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>        b[<span class="dv">0</span>]  <span class="op">=</span> b0</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>        b[<span class="op">-</span><span class="dv">1</span>] <span class="op">=</span> bc</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>        LL[i, j] <span class="op">=</span> poisson_regression_loglikelihood(b, y, X_reg)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-fig-loglik-2d" class="cell" data-fig-height="5" data-fig-width="7" data-execution_count="19">
<div class="cell-output cell-output-display">
<div id="fig-loglik-2d" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-loglik-2d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="hw3_questions_files/figure-html/fig-loglik-2d-output-1.png" width="648" height="461" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-loglik-2d-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Log-likelihood contours over the intercept and customer coefficient. Elliptical shape reflects asymptotic normality of the MLE.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="a-confidence-interval-on-the-average-treatment-effect" class="level3">
<h3 class="anchored" data-anchor-id="a-confidence-interval-on-the-average-treatment-effect">A Confidence Interval on the Average Treatment Effect</h3>
<p>The ATE reported above is a point estimate. To quantify its uncertainty we apply the <strong>delta method</strong>: for a smooth function <span class="math inline">\(g(\boldsymbol\beta)\)</span>,</p>
<p><span class="math display">\[\text{Var}\bigl(g(\hat{\boldsymbol\beta})\bigr) \;\approx\;
\nabla g(\hat{\boldsymbol\beta})^\top \;\hat\Sigma\;
\nabla g(\hat{\boldsymbol\beta})\]</span></p>
<p>where <span class="math inline">\(\hat\Sigma = \mathbf{I}(\hat{\boldsymbol\beta})^{-1}\)</span> is the estimated covariance matrix of the MLE. Here <span class="math inline">\(g(\boldsymbol\beta) = \frac{1}{n}\sum_i
\bigl[\exp(X_{1i}'\boldsymbol\beta) - \exp(X_{0i}'\boldsymbol\beta)\bigr]\)</span>, whose gradient with respect to <span class="math inline">\(\boldsymbol\beta\)</span> is</p>
<p><span class="math display">\[\nabla g(\boldsymbol\beta) = \frac{1}{n}\sum_i
\bigl[\hat\lambda_{1i}\,X_{1i} - \hat\lambda_{0i}\,X_{0i}\bigr]\]</span></p>
<div id="ate-ci" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recompute counterfactual predictions (self-contained)</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>X0 <span class="op">=</span> X_df.copy()<span class="op">;</span>  X0[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>X1 <span class="op">=</span> X_df.copy()<span class="op">;</span>  X1[<span class="st">"iscustomer"</span>] <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>lam_0 <span class="op">=</span> np.exp(X0.values <span class="op">@</span> glm_result.params.values)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>lam_1 <span class="op">=</span> np.exp(X1.values <span class="op">@</span> glm_result.params.values)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>ate   <span class="op">=</span> <span class="bu">float</span>(np.mean(lam_1 <span class="op">-</span> lam_0))</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Gradient of ATE with respect to β (delta method)</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>grad_ate <span class="op">=</span> (<span class="dv">1</span> <span class="op">/</span> <span class="bu">len</span>(df)) <span class="op">*</span> (</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    (X1.values <span class="op">*</span> lam_1[:, np.newaxis]) <span class="op">-</span></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    (X0.values <span class="op">*</span> lam_0[:, np.newaxis])</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>se_ate  <span class="op">=</span> <span class="bu">float</span>(np.sqrt(grad_ate <span class="op">@</span> cov_mle <span class="op">@</span> grad_ate))</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>ci_low  <span class="op">=</span> ate <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> se_ate</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>ci_high <span class="op">=</span> ate <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> se_ate</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ATE point estimate : </span><span class="sc">{</span>ate<span class="sc">:.4f}</span><span class="ss"> additional patents"</span>)</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Delta method SE    : </span><span class="sc">{</span>se_ate<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"95% CI             : (</span><span class="sc">{</span>ci_low<span class="sc">:.4f}</span><span class="ss">,  </span><span class="sc">{</span>ci_high<span class="sc">:.4f}</span><span class="ss">)"</span>)</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Relative uplift    : </span><span class="sc">{</span>ate <span class="op">/</span> lam_0<span class="sc">.</span>mean() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%  "</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(CI: </span><span class="sc">{</span>ci_low <span class="op">/</span> lam_0<span class="sc">.</span>mean() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">% – "</span></span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>ci_high <span class="op">/</span> lam_0<span class="sc">.</span>mean() <span class="op">*</span> <span class="dv">100</span><span class="sc">:.1f}</span><span class="ss">%)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>ATE point estimate : 0.7928 additional patents
Delta method SE    : 0.1225
95% CI             : (0.5526,  1.0329)
Relative uplift    : 23.1%  (CI: 16.1% – 30.1%)</code></pre>
</div>
</div>
<p>The delta method confidence interval places a lower and upper bound on the plausible range of the software’s benefit that properly propagates the uncertainty in all eight estimated coefficients through to the final ATE estimate. Both bounds lying above zero strengthens the conclusion significantly: it is not just the point estimate that favours Blueprinty, but the entire 95% confidence interval.</p>
</section>
<section id="methodological-limitations" class="level3">
<h3 class="anchored" data-anchor-id="methodological-limitations">Methodological Limitations</h3>
<p>Poisson regression is a natural and well-justified model for the nature of this dataset, but we need to be transparent about two limitations.</p>
<p><strong>Overdispersion.</strong> If the variance of patent counts substantially exceeds the mean, as shown in the check earlier, the Poisson mean-variance equality is violated. Standard errors will be underestimated, and the <span class="math inline">\(p\)</span>-values and confidence intervals reported in the table will be anti-conservative. Quasi-Poisson or negative binomial regression would relax this constraint and serve as important robustness checks. If the customer coefficient retains similar magnitude and significance under those specifications, the marketing claim becomes easier to defend.</p>
<p><strong>Observational identification.</strong> Even when we control for age and region, unobserved variables such as R&amp;D budget, patent department headcount, and management quality may simultaneously predict Blueprinty adoption and patent success. The MLE is the best estimator <em>within</em> the Poisson regression model, but no amount of statistical sophistication can substitute for the randomization that would cleanly identify a causal effect. The ATE should be interpreted as the average association attributable to customer status after observable controls, not as a structural causal quantity. A randomized pilot study, a difference-in-differences design using pre- and post-adoption data, or an instrumental variable based on regional Blueprinty sales penetration would all represent meaningful steps toward a more credible causal claim.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Trevor Sullivan</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>