<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.13">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Trevor Sullivan">
<meta name="dcterms.date" content="2026-04-21">

<title>Replication of Angrist and Lavy (1999) – Trevor’s Website</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-ac077c1e730dfeb5e42400639d17284e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-f8875d2965223058efa6f79d6d895f74.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Trevor’s Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> <i class="bi bi-person-circle" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resume.html"> <i class="bi bi-file-earmark-check" role="img">
</i> 
<span class="menu-text">Resume</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> <i class="bi bi-collection" role="img">
</i> 
<span class="menu-text">Projects</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#main-analysis" id="toc-main-analysis" class="nav-link" data-scroll-target="#main-analysis">Main Analysis</a>
  <ul class="collapse">
  <li><a href="#load-the-fifth-grade-sample" id="toc-load-the-fifth-grade-sample" class="nav-link" data-scroll-target="#load-the-fifth-grade-sample">Load the fifth-grade sample</a></li>
  <li><a href="#identify-the-core-variables" id="toc-identify-the-core-variables" class="nav-link" data-scroll-target="#identify-the-core-variables">Identify the core variables</a></li>
  <li><a href="#construct-the-maimonides-rule-instrument" id="toc-construct-the-maimonides-rule-instrument" class="nav-link" data-scroll-target="#construct-the-maimonides-rule-instrument">Construct the Maimonides-rule instrument</a></li>
  <li><a href="#first-stage-relationship" id="toc-first-stage-relationship" class="nav-link" data-scroll-target="#first-stage-relationship">First-stage relationship</a></li>
  <li><a href="#reduced-form-relationship" id="toc-reduced-form-relationship" class="nav-link" data-scroll-target="#reduced-form-relationship">Reduced-form relationship</a></li>
  <li><a href="#estimate-the-main-2sls-specification" id="toc-estimate-the-main-2sls-specification" class="nav-link" data-scroll-target="#estimate-the-main-2sls-specification">Estimate the main 2SLS specification</a></li>
  <li><a href="#add-a-quadratic-control-for-enrollment" id="toc-add-a-quadratic-control-for-enrollment" class="nav-link" data-scroll-target="#add-a-quadratic-control-for-enrollment">Add a quadratic control for enrollment</a></li>
  <li><a href="#compare-reading-and-math-outcomes" id="toc-compare-reading-and-math-outcomes" class="nav-link" data-scroll-target="#compare-reading-and-math-outcomes">Compare reading and math outcomes</a></li>
  <li><a href="#restrict-to-the-discontinuity-sample" id="toc-restrict-to-the-discontinuity-sample" class="nav-link" data-scroll-target="#restrict-to-the-discontinuity-sample">Restrict to the discontinuity sample</a></li>
  <li><a href="#cluster-standard-errors-at-the-school-level" id="toc-cluster-standard-errors-at-the-school-level" class="nav-link" data-scroll-target="#cluster-standard-errors-at-the-school-level">Cluster standard errors at the school level</a></li>
  </ul></li>
  <li><a href="#additional-analysis-visualizing-the-identification-strategy" id="toc-additional-analysis-visualizing-the-identification-strategy" class="nav-link" data-scroll-target="#additional-analysis-visualizing-the-identification-strategy">Additional Analysis: Visualizing the Identification Strategy</a>
  <ul class="collapse">
  <li><a href="#why-this-strengthens-the-causal-interpretation" id="toc-why-this-strengthens-the-causal-interpretation" class="nav-link" data-scroll-target="#why-this-strengthens-the-causal-interpretation">Why this strengthens the causal interpretation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Replication of Angrist and Lavy (1999)</h1>
<p class="subtitle lead">USING MAIMONIDES’ RULE TO ESTIMATE THE EFFECT OF CLASS SIZE ON SCHOLASTIC ACHIEVEMENT*</p>
</div>



<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Trevor Sullivan </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>In Israel, schools followed Maimonides’ rule, which capped class size at 40 students. That creates sharp jumps in class size when enrollment crosses thresholds like 40 or 80. For example, 40 students can be taught in one class, but 41 students must be split into two smaller classes. Angrist and Lavy use this rule as an instrumental variable to study whether those changes in class sizes affect the achievement of students. The goal of this study is to estimate the causal effect of class size on students’ test scores, and not just identify a simple correlation.</p>
<p>The motivation for the design of this study is that earlier research on class size and difficult to interpret, because class size is often confounded with other factors like student disadvantage, remedial placement, and school quality. The authors want to move around that problem by exploiting the nonlinear pattern created by Maimonides’ rule.</p>
</section>
<section id="main-analysis" class="level2">
<h2 class="anchored" data-anchor-id="main-analysis">Main Analysis</h2>
<div id="2705eadc" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pathlib <span class="im">import</span> Path</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> linearmodels.iv <span class="im">import</span> IV2SLS</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="load-the-fifth-grade-sample" class="level3">
<h3 class="anchored" data-anchor-id="load-the-fifth-grade-sample">Load the fifth-grade sample</h3>
<div id="b31bcf4b" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load in dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df5 <span class="op">=</span> pd.read_stata(data_dir <span class="op">/</span> <span class="st">"final5.dta"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick inspection</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape: </span><span class="sc">{</span>df5<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Column names: </span><span class="sc">{</span>df5<span class="sc">.</span>columns<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>df5.head()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape: (2029, 51)
Column names: ['schlcode', 'c_size', 'c_boys', 'c_girls', 'c_numcl', 'c_pik', 'c_status', 'c_leom', 'c_tip', 'c_num5rd', 'c_type', 'flgrm5', 'mrkgrm5', 'ngrm5', 'flmth5', 'mrkmth5', 'nmth5', 'towncode', 'townname', 'popcode', 'tip_a', 'grade', 'classid', 'classize', '_type_', '_freq_', 'cohsize', 'mathsize', 'avgmath', 'passmath', 'verbsize', 'avgverb', 'passverb', 'studchk', 'misskov2', 'missagg', 'nmiss_k', 'nmiss_a', 'classct', 'math_n', 'flmath_n', 'nmath_n', 'verb_n', 'flverb_n', 'nverb_n', 'impute', 'nverb_m', 'nmath_m', 'tip_s', 'townid', 'tipuach']</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="3">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">schlcode</th>
<th data-quarto-table-cell-role="th">c_size</th>
<th data-quarto-table-cell-role="th">c_boys</th>
<th data-quarto-table-cell-role="th">c_girls</th>
<th data-quarto-table-cell-role="th">c_numcl</th>
<th data-quarto-table-cell-role="th">c_pik</th>
<th data-quarto-table-cell-role="th">c_status</th>
<th data-quarto-table-cell-role="th">c_leom</th>
<th data-quarto-table-cell-role="th">c_tip</th>
<th data-quarto-table-cell-role="th">c_num5rd</th>
<th data-quarto-table-cell-role="th">...</th>
<th data-quarto-table-cell-role="th">nmath_n</th>
<th data-quarto-table-cell-role="th">verb_n</th>
<th data-quarto-table-cell-role="th">flverb_n</th>
<th data-quarto-table-cell-role="th">nverb_n</th>
<th data-quarto-table-cell-role="th">impute</th>
<th data-quarto-table-cell-role="th">nverb_m</th>
<th data-quarto-table-cell-role="th">nmath_m</th>
<th data-quarto-table-cell-role="th">tip_s</th>
<th data-quarto-table-cell-role="th">townid</th>
<th data-quarto-table-cell-role="th">tipuach</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>11005</td>
<td>54</td>
<td>24</td>
<td>30</td>
<td>9</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>5</td>
<td>2</td>
<td>...</td>
<td>55.0</td>
<td>72.744728</td>
<td>27.256363</td>
<td>55.0</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>24.0</td>
<td>26104.0</td>
<td>24</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>11005</td>
<td>54</td>
<td>24</td>
<td>30</td>
<td>9</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>5</td>
<td>2</td>
<td>...</td>
<td>55.0</td>
<td>72.744728</td>
<td>27.256363</td>
<td>55.0</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>24.0</td>
<td>26104.0</td>
<td>24</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>11006</td>
<td>37</td>
<td>21</td>
<td>16</td>
<td>12</td>
<td>2</td>
<td>2</td>
<td>1</td>
<td>7</td>
<td>2</td>
<td>...</td>
<td>15.0</td>
<td>75.470001</td>
<td>20.000000</td>
<td>15.0</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>38.0</td>
<td>26104.0</td>
<td>38</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>11006</td>
<td>37</td>
<td>21</td>
<td>16</td>
<td>12</td>
<td>2</td>
<td>2</td>
<td>1</td>
<td>7</td>
<td>2</td>
<td>...</td>
<td>15.0</td>
<td>75.470001</td>
<td>20.000000</td>
<td>15.0</td>
<td>1</td>
<td>20.0</td>
<td>20.0</td>
<td>38.0</td>
<td>26104.0</td>
<td>38</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>11009</td>
<td>32</td>
<td>17</td>
<td>15</td>
<td>6</td>
<td>1</td>
<td>2</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>...</td>
<td>32.0</td>
<td>73.970001</td>
<td>40.599998</td>
<td>32.0</td>
<td>0</td>
<td>NaN</td>
<td>NaN</td>
<td>6.0</td>
<td>4622.0</td>
<td>6</td>
</tr>
</tbody>
</table>

<p>5 rows × 51 columns</p>
</div>
</div>
</div>
<p>I begin with the grade-specific Stata file rather than combining samples across grades. This matches the structure of the original study, which reports results separately for fourth and fifth graders. For the main replication, I start with <code>final5.dta</code>, since the paper’s strongest and most prominent findings are for fifth-grade outcomes, especially reading achievement.</p>
<p>Before estimating any models, I inspect the dataset to identify the variables corresponding to observed class size, enrollment, test scores, and the measure of student disadvantage. This step is important because even when working from the authors’ original files, variable names may be abbreviated or coded differently than the terminology used in the paper. Confirming these mappings up front makes the later replication steps easier to interpret and reduces the risk of specification errors.</p>
</section>
<section id="identify-the-core-variables" class="level3">
<h3 class="anchored" data-anchor-id="identify-the-core-variables">Identify the core variables</h3>
<div id="745fd68e" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep the core variables for replication</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>g5 <span class="op">=</span> df5[[<span class="st">"classize"</span>, <span class="st">"cohsize"</span>, <span class="st">"avgverb"</span>, <span class="st">"avgmath"</span>, <span class="st">"tipuach"</span>, <span class="st">"schlcode"</span>]].copy()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop missing values in the main analysis variables</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>g5 <span class="op">=</span> g5.dropna(subset<span class="op">=</span>[<span class="st">"classize"</span>, <span class="st">"cohsize"</span>, <span class="st">"avgverb"</span>, <span class="st">"avgmath"</span>, <span class="st">"tipuach"</span>]).copy()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Shape: </span><span class="sc">{</span>g5<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>g5.describe().T</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape: (2024, 6)</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="4">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">25%</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">75%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">classize</th>
<td>2024.0</td>
<td>29.954545</td>
<td>6.600073</td>
<td>5.000000</td>
<td>26.000000</td>
<td>31.000000</td>
<td>35.000000</td>
<td>47.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">cohsize</th>
<td>2024.0</td>
<td>74.223320</td>
<td>37.211710</td>
<td>5.000000</td>
<td>48.000000</td>
<td>69.000000</td>
<td>96.000000</td>
<td>217.000000</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">avgverb</th>
<td>2024.0</td>
<td>74.445480</td>
<td>8.077354</td>
<td>34.799999</td>
<td>69.857500</td>
<td>75.430000</td>
<td>79.847000</td>
<td>187.606003</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">avgmath</th>
<td>2024.0</td>
<td>67.323013</td>
<td>10.032691</td>
<td>0.000000</td>
<td>61.137501</td>
<td>67.799999</td>
<td>74.094997</td>
<td>181.246002</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">tipuach</th>
<td>2024.0</td>
<td>14.095356</td>
<td>13.492471</td>
<td>0.000000</td>
<td>4.000000</td>
<td>10.000000</td>
<td>19.250000</td>
<td>76.000000</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">schlcode</th>
<td>2024.0</td>
<td>39607.332016</td>
<td>15280.974897</td>
<td>11005.000000</td>
<td>31037.000000</td>
<td>41213.000000</td>
<td>51203.000000</td>
<td>61365.000000</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="construct-the-maimonides-rule-instrument" class="level3">
<h3 class="anchored" data-anchor-id="construct-the-maimonides-rule-instrument">Construct the Maimonides-rule instrument</h3>
<p>The key source of identification in the paper is the class-size rule attributed to Maimonides, which caps classes at 40 students. This rule implies a nonlinear relationship between cohort enrollment and predicted class size. If a grade has <span class="math inline">\(e_s\)</span> students enrolled, then the predicted class size is</p>
<p><span class="math display">\[
f_s = \frac{e_s}{\left\lfloor \frac{e_s - 1}{40} \right\rfloor + 1}.
\]</span></p>
<p>This formula captures the fact that a cohort of up to 40 students can remain in one class, while a cohort of 41 students must be split into two classes. More generally, the denominator gives the number of classes implied by the 40-student cap. Following the paper, I use this rule-based predicted class size as an instrument for actual class size.</p>
<div id="32ceb05b" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Construct Maimonides' rule predicted class size</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># f_sc = enrollment / ( floor((enrollment - 1)/40) + 1 )</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>g5[<span class="st">"pred_class_size"</span>] <span class="op">=</span> g5[<span class="st">"cohsize"</span>] <span class="op">/</span> (np.floor((g5[<span class="st">"cohsize"</span>] <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> <span class="dv">40</span>) <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>g5[[<span class="st">"cohsize"</span>, <span class="st">"pred_class_size"</span>, <span class="st">"classize"</span>]].head(<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">cohsize</th>
<th data-quarto-table-cell-role="th">pred_class_size</th>
<th data-quarto-table-cell-role="th">classize</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">0</th>
<td>54</td>
<td>27.0</td>
<td>28</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1</th>
<td>54</td>
<td>27.0</td>
<td>26</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2</th>
<td>37</td>
<td>37.0</td>
<td>22</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">3</th>
<td>37</td>
<td>37.0</td>
<td>15</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">4</th>
<td>32</td>
<td>32.0</td>
<td>32</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">5</th>
<td>68</td>
<td>34.0</td>
<td>34</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">6</th>
<td>68</td>
<td>34.0</td>
<td>34</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">7</th>
<td>87</td>
<td>29.0</td>
<td>30</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">8</th>
<td>87</td>
<td>29.0</td>
<td>26</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">9</th>
<td>87</td>
<td>29.0</td>
<td>31</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</section>
<section id="first-stage-relationship" class="level3">
<h3 class="anchored" data-anchor-id="first-stage-relationship">First-stage relationship</h3>
<p>The first empirical step is to verify the relevance of the instrument. In a fuzzy regression discontinuity framework, crossing the enrollment thresholds does not perfectly determine actual class size, but it should still shift class size strongly and systematically. This is the first-stage relationship.</p>
<p>Formally, the first stage can be written as</p>
<p><span class="math display">\[
\text{classize}_{sc} = \pi_0 + \pi_1 f_s + \pi_2 \text{tipuach}_s + \pi_3 \text{cohsize}_s + u_{sc},
\]</span></p>
<p>where <span class="math inline">\(f_s\)</span> is predicted class size from Maimonides’ rule. A strong negative or positive association between the instrument and observed class size is essential, because the IV estimates rely on this rule-based variation to identify the causal effect of class size.</p>
<div id="aea8b242" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quick first-stage check with OLS</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>X_fs <span class="op">=</span> g5[[<span class="st">"pred_class_size"</span>, <span class="st">"tipuach"</span>, <span class="st">"cohsize"</span>]].copy()</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>X_fs <span class="op">=</span> sm.add_constant(X_fs)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>first_stage <span class="op">=</span> sm.OLS(g5[<span class="st">"classize"</span>], X_fs).fit(cov_type<span class="op">=</span><span class="st">"HC1"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(first_stage.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:               classize   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     1991.
Date:                Tue, 21 Apr 2026   Prob (F-statistic):               0.00
Time:                        16:28:13   Log-Likelihood:                -5646.3
No. Observations:                2024   AIC:                         1.130e+04
Df Residuals:                    2020   BIC:                         1.132e+04
Df Model:                           3                                         
Covariance Type:                  HC1                                         
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const               7.4148      0.664     11.159      0.000       6.112       8.717
pred_class_size     0.6565      0.030     22.132      0.000       0.598       0.715
tipuach            -0.0348      0.007     -4.774      0.000      -0.049      -0.021
cohsize             0.0392      0.004      9.520      0.000       0.031       0.047
==============================================================================
Omnibus:                      727.891   Durbin-Watson:                   1.421
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             6866.285
Skew:                          -1.417   Prob(JB):                         0.00
Kurtosis:                      11.566   Cond. No.                         520.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the first-stage results
</div>
</div>
<div class="callout-body-container callout-body">
<p>The first-stage regression confirms that the Maimonides-rule instrument is highly relevant for explaining observed class size. The coefficient on <code>pred_class_size</code> is <strong>0.6565</strong> with a very small standard error, indicating a strong positive relationship between rule-predicted class size and actual class size. In other words, when the institutional rule predicts larger classes, schools do in fact tend to have larger observed classes.</p>
<p>Formally, the estimated first stage is</p>
<p><span class="math display">\[
\text{classize}_{sc} = \pi_0 + \pi_1 \text{pred\_class\_size}_{s} + \pi_2 \text{tipuach}_{s} + \pi_3 \text{cohsize}_{s} + u_{sc},
\]</span></p>
<p>with <span class="math inline">\(\hat{\pi}_1 = 0.6565\)</span>. This means that a one-student increase in predicted class size is associated with about a <strong>0.66 student increase</strong> in actual class size, conditional on disadvantage and cohort size.</p>
<p>This is exactly what the replication needs at this stage: a strong first stage. Since the IV strategy relies on variation in actual class size generated by the rule of 40, the fact that the instrument enters so strongly supports the credibility of the 2SLS design.</p>
</div>
</div>
</section>
<section id="reduced-form-relationship" class="level3">
<h3 class="anchored" data-anchor-id="reduced-form-relationship">Reduced-form relationship</h3>
<p>After verifying that the instrument predicts actual class size, I estimate the reduced-form relationship between the rule-based instrument and student achievement. This asks whether the variation in class size induced by Maimonides’ rule is associated with systematic changes in test scores.</p>
<p>The reduced form is useful because it captures the total effect of the instrument on outcomes before dividing by the first-stage relationship. In notation, the reduced-form regression for reading is</p>
<p><span class="math display">\[
\text{avgverb}_{sc} = \rho_0 + \rho_1 f_s + \rho_2 \text{tipuach}_s + \rho_3 \text{cohsize}_s + \varepsilon_{sc}.
\]</span></p>
<p>If smaller classes improve achievement, then the discontinuities induced by the rule should generate corresponding shifts in test performance.</p>
<div id="beac1cb3" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reduced form: reading score on predicted class size + controls</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>X_rf <span class="op">=</span> g5[[<span class="st">"pred_class_size"</span>, <span class="st">"tipuach"</span>, <span class="st">"cohsize"</span>]].copy()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>X_rf <span class="op">=</span> sm.add_constant(X_rf)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>reduced_form <span class="op">=</span> sm.OLS(g5[<span class="st">"avgverb"</span>], X_rf).fit(cov_type<span class="op">=</span><span class="st">"HC1"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(reduced_form.summary())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:                avgverb   R-squared:                       0.333
Model:                            OLS   Adj. R-squared:                  0.332
Method:                 Least Squares   F-statistic:                     249.2
Date:                Tue, 21 Apr 2026   Prob (F-statistic):          1.34e-137
Time:                        16:28:13   Log-Likelihood:                -6690.2
No. Observations:                2024   AIC:                         1.339e+04
Df Residuals:                    2020   BIC:                         1.341e+04
Df Model:                           3                                         
Covariance Type:                  HC1                                         
===================================================================================
                      coef    std err          z      P&gt;|z|      [0.025      0.975]
-----------------------------------------------------------------------------------
const              83.2212      0.832    100.019      0.000      81.590      84.852
pred_class_size    -0.1524      0.031     -4.854      0.000      -0.214      -0.091
tipuach            -0.3518      0.014    -25.521      0.000      -0.379      -0.325
cohsize             0.0115      0.005      2.371      0.018       0.002       0.021
==============================================================================
Omnibus:                     1437.652   Durbin-Watson:                   1.528
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           210326.812
Skew:                           2.424   Prob(JB):                         0.00
Kurtosis:                      52.704   Cond. No.                         520.
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC1)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the reduced-form results
</div>
</div>
<div class="callout-body-container callout-body">
<p>The reduced-form regression shows that higher predicted class size is associated with lower fifth-grade reading performance. The coefficient on <code>pred_class_size</code> is <strong>-0.1524</strong>, implying that when the rule predicts larger classes, average verbal scores fall.</p>
<p>This relationship can be written as</p>
<p><span class="math display">\[
\text{avgverb}_{sc} = \rho_0 + \rho_1 \text{pred\_class\_size}_{s} + \rho_2 \text{tipuach}_{s} + \rho_3 \text{cohsize}_{s} + \varepsilon_{sc},
\]</span></p>
<p>with <span class="math inline">\(\hat{\rho}_1 = -0.1524\)</span>. The negative sign is consistent with the paper’s main intuition: the enrollment cutoffs created by Maimonides’ rule shift class size in a way that also shifts student achievement.</p>
<p>Essentially, the reduced form is useful because it shows that the instrument matters not only for treatment assignment, but also for outcomes. This is the key connection between the first stage and the IV estimate. The negative reduced-form coefficient already suggests that smaller classes improve reading scores in the fifth-grade sample.</p>
</div>
</div>
</section>
<section id="estimate-the-main-2sls-specification" class="level3">
<h3 class="anchored" data-anchor-id="estimate-the-main-2sls-specification">Estimate the main 2SLS specification</h3>
<p>Next, I will estimate the main instrumental variables model, using predicted class size from Maimonides’ rule as an instrument for observed class size. This is the central replication step because it corresponds directly to the paper’s main causal claim.</p>
<p>The second-stage equation can be written as</p>
<p><span class="math display">\[
\text{avgverb}_{sc} = \beta_0 + \beta_1 \text{classize}_{sc} + \beta_2 \text{tipuach}_s + \beta_3 \text{cohsize}_s + \eta_{sc},
\]</span></p>
<p>where <code>classize</code> is treated as endogenous and instrumented with <span class="math inline">\(f_s\)</span>. The coefficient of interest is <span class="math inline">\(\beta_1\)</span>. A negative estimate implies that reducing class size increases average verbal achievement, which is the core finding reported in the paper for fifth graders.</p>
<div id="81eec172" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Main 2SLS specification: fifth-grade reading</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>iv_reading <span class="op">=</span> IV2SLS.from_formula(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avgverb ~ 1 + tipuach + cohsize + [classize ~ pred_class_size]"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>g5</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>).fit(cov_type<span class="op">=</span><span class="st">"robust"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iv_reading.summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          IV-2SLS Estimation Summary                          
==============================================================================
Dep. Variable:                avgverb   R-squared:                      0.3084
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3074
No. Observations:                2024   F-statistic:                    699.67
Date:                Tue, Apr 21 2026   P-value (F-stat)                0.0000
Time:                        16:28:13   Distribution:                  chi2(3)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      84.942     1.2156     69.878     0.0000      82.560      87.325
tipuach       -0.3599     0.0143    -25.202     0.0000     -0.3878     -0.3319
cohsize        0.0206     0.0065     3.1739     0.0015      0.0079      0.0333
classize      -0.2321     0.0503    -4.6141     0.0000     -0.3307     -0.1335
==============================================================================

Endogenous: classize
Instruments: pred_class_size
Robust Covariance (Heteroskedastic)
Debiased: False</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the main 2SLS result for fifth-grade reading
</div>
</div>
<div class="callout-body-container callout-body">
<p>The main IV estimate implies a statistically significant negative effect of class size on fifth-grade reading achievement. The coefficient on <code>classize</code> is <strong>-0.2321</strong>, which means that increasing class size by one student lowers the average verbal score by about <strong>0.23 points</strong>, holding disadvantage and cohort size constant.</p>
<p>The second-stage equation is</p>
<p><span class="math display">\[
\text{avgverb}_{sc} = \beta_0 + \beta_1 \text{classize}_{sc} + \beta_2 \text{tipuach}_{s} + \beta_3 \text{cohsize}_{s} + \eta_{sc},
\]</span></p>
<p>where <code>classize</code> is instrumented using <code>pred_class_size</code>. The estimate <span class="math inline">\(\hat{\beta}_1 = -0.2321\)</span> is close to the values reported in Angrist and Lavy for fifth-grade reading, where their preferred specifications are generally in the range of roughly <span class="math inline">\(-0.16\)</span> to <span class="math inline">\(-0.28\)</span>.</p>
<p>This is therefore a successful replication of one of the paper’s central findings. The sign, magnitude, and statistical significance all line up with the published result: <strong>smaller classes lead to higher reading achievement for fifth graders</strong>.</p>
</div>
</div>
</section>
<section id="add-a-quadratic-control-for-enrollment" class="level3">
<h3 class="anchored" data-anchor-id="add-a-quadratic-control-for-enrollment">Add a quadratic control for enrollment</h3>
<p>One concern in this design is that cohort enrollment may affect test scores through channels other than class size. To address this, the paper considers specifications that include increasingly flexible controls for enrollment. I begin with a quadratic specification by adding <span class="math inline">\(\text{cohsize}^2 / 100\)</span> to the model.</p>
<p>The motivation is that the identifying assumption is not that enrollment is random, but rather that any non-class-size effects of enrollment are smooth. The discontinuities generated by the rule then provide the source of exogenous variation. The corresponding specification becomes</p>
<p><span class="math display">\[
\text{avgverb}_{sc} =
\beta_0 + \beta_1 \text{classize}_{sc}
+ \beta_2 \text{tipuach}_s
+ \beta_3 \text{cohsize}_s
+ \beta_4 \frac{\text{cohsize}_s^2}{100}
+ \eta_{sc}.
\]</span></p>
<p>This helps check whether the estimated class-size effect is robust to a more flexible control for enrollment.</p>
<div id="26cbb9f9" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2SLS with quadratic enrollment control</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>g5[<span class="st">"cohsize_sq_100"</span>] <span class="op">=</span> (g5[<span class="st">"cohsize"</span>] <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> <span class="dv">100</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>iv_reading_quad <span class="op">=</span> IV2SLS.from_formula(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avgverb ~ 1 + tipuach + cohsize + cohsize_sq_100 + [classize ~ pred_class_size]"</span>,</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>g5</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>).fit(cov_type<span class="op">=</span><span class="st">"robust"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iv_reading_quad.summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          IV-2SLS Estimation Summary                          
==============================================================================
Dep. Variable:                avgverb   R-squared:                      0.3084
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3070
No. Observations:                2024   F-statistic:                    699.71
Date:                Tue, Apr 21 2026   P-value (F-stat)                0.0000
Time:                        16:28:13   Distribution:                  chi2(4)
Cov. Estimator:                robust                                         
                                                                              
                               Parameter Estimates                                
==================================================================================
                Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
----------------------------------------------------------------------------------
Intercept          84.940     1.2243     69.376     0.0000      82.540      87.340
tipuach           -0.3599     0.0143    -25.133     0.0000     -0.3879     -0.3318
cohsize            0.0207     0.0063     3.2886     0.0010      0.0083      0.0330
cohsize_sq_100 -7.102e-05     0.0018    -0.0401     0.9681     -0.0035      0.0034
classize          -0.2320     0.0507    -4.5738     0.0000     -0.3315     -0.1326
==================================================================================

Endogenous: classize
Instruments: pred_class_size
Robust Covariance (Heteroskedastic)
Debiased: False</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the 2SLS result with quadratic enrollment controls
</div>
</div>
<div class="callout-body-container callout-body">
<p>Adding a quadratic term in cohort size leaves the estimated class-size effect essentially unchanged. The coefficient on <code>classize</code> is <strong>-0.2320</strong>, compared with <strong>-0.2321</strong> in the linear specification. The coefficient on the quadratic term itself is extremely small and statistically insignificant.</p>
<p>This specification is helpful because one concern in regression discontinuity or IV designs based on enrollment is that cohort size may affect outcomes through nonlinear channels unrelated to class size. By estimating</p>
<p><span class="math display">\[
\text{avgverb}_{sc}
= \beta_0 + \beta_1 \text{classize}_{sc}
+ \beta_2 \text{tipuach}_{s}
+ \beta_3 \text{cohsize}_{s}
+ \beta_4 \frac{\text{cohsize}_{s}^{2}}{100}
+ \eta_{sc},
\]</span></p>
<p>I allow for a more flexible smooth relationship between enrollment and achievement.</p>
<p>The fact that the estimated effect of class size is virtually identical across the linear and quadratic specifications suggests that the result is not being driven by a misspecified control for cohort size. This strengthens the interpretation that the discontinuous variation induced by Maimonides’ rule is identifying a genuine causal effect.</p>
</div>
</div>
</section>
<section id="compare-reading-and-math-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="compare-reading-and-math-outcomes">Compare reading and math outcomes</h3>
<p>After estimating the model for verbal achievement, I repeat the same 2SLS procedure using average math scores as the dependent variable. This comparison is useful because the paper reports stronger and more consistent evidence for some outcomes than for others. Replicating both outcomes helps determine whether the data reproduce the same qualitative pattern.</p>
<p>Using the same instrument and control set also makes the comparison clean: any difference in results between reading and math reflects differences in how class size affects those outcomes, rather than differences in specification.</p>
<div id="e515ae29" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2SLS for math, if you want to compare to the paper</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>iv_math <span class="op">=</span> IV2SLS.from_formula(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avgmath ~ 1 + tipuach + cohsize + [classize ~ pred_class_size]"</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>g5</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>).fit(cov_type<span class="op">=</span><span class="st">"robust"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iv_math.summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          IV-2SLS Estimation Summary                          
==============================================================================
Dep. Variable:                avgmath   R-squared:                      0.2130
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2118
No. Observations:                2024   F-statistic:                    538.28
Date:                Tue, Apr 21 2026   P-value (F-stat)                0.0000
Time:                        16:28:14   Distribution:                  chi2(3)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      74.123     1.7002     43.595     0.0000      70.790      77.455
tipuach       -0.3344     0.0179    -18.706     0.0000     -0.3694     -0.2993
cohsize        0.0392     0.0082     4.7814     0.0000      0.0231      0.0552
classize      -0.1667     0.0660    -2.5269     0.0115     -0.2960     -0.0374
==============================================================================

Endogenous: classize
Instruments: pred_class_size
Robust Covariance (Heteroskedastic)
Debiased: False</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the 2SLS result for fifth-grade math
</div>
</div>
<div class="callout-body-container callout-body">
<p>The IV estimate for math is also negative and statistically significant. The coefficient on <code>classize</code> is <strong>-0.1667</strong>, implying that an increase of one student in class size lowers average math scores by about <strong>0.17 points</strong>.</p>
<p>This result is somewhat smaller in magnitude than the corresponding reading estimate, but it points in the same direction. In practical terms, both outcomes suggest that smaller classes improve student performance, with the effect appearing somewhat stronger for reading than for math in this sample.</p>
<p>This pattern also aligns well with the paper. Angrist and Lavy find especially clear evidence for fifth graders, and the math results become more negative once enrollment controls are included. My replication therefore supports the same conclusion: the institutional variation generated by the rule of 40 implies that smaller fifth-grade classes improve achievement.</p>
</div>
</div>
</section>
<section id="restrict-to-the-discontinuity-sample" class="level3">
<h3 class="anchored" data-anchor-id="restrict-to-the-discontinuity-sample">Restrict to the discontinuity sample</h3>
<p>To move closer to a local regression discontinuity interpretation, I restrict the sample to schools with enrollment close to the key cutoffs. Following the paper, this discontinuity sample includes observations with cohort enrollment in the intervals <span class="math inline">\([36,45]\)</span>, <span class="math inline">\([76,85]\)</span>, and <span class="math inline">\([116,125]\)</span>.</p>
<p>The logic is that observations near the thresholds are more comparable, while still preserving the discontinuous jumps in predicted class size induced by the rule. This sample restriction emphasizes the quasi-experimental variation at the cutoffs and reduces reliance on functional-form assumptions away from the discontinuities.</p>
<div id="d312540c" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Discontinuity sample used in the paper:</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># cohsize in [36,45], [76,85], [116,125]</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>g5_disc <span class="op">=</span> g5[</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    g5[<span class="st">"cohsize"</span>].between(<span class="dv">36</span>, <span class="dv">45</span>) <span class="op">|</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    g5[<span class="st">"cohsize"</span>].between(<span class="dv">76</span>, <span class="dv">85</span>) <span class="op">|</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    g5[<span class="st">"cohsize"</span>].between(<span class="dv">116</span>, <span class="dv">125</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>].copy()</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(g5_disc.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>(431, 8)</code></pre>
</div>
</div>
<div id="fd775550" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2SLS in discontinuity sample</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>iv_reading_disc <span class="op">=</span> IV2SLS.from_formula(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avgverb ~ 1 + tipuach + cohsize + [classize ~ pred_class_size]"</span>,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>g5_disc</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>).fit(cov_type<span class="op">=</span><span class="st">"robust"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iv_reading_disc.summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          IV-2SLS Estimation Summary                          
==============================================================================
Dep. Variable:                avgverb   R-squared:                      0.3013
Estimator:                    IV-2SLS   Adj. R-squared:                 0.2964
No. Observations:                 431   F-statistic:                    182.55
Date:                Tue, Apr 21 2026   P-value (F-stat)                0.0000
Time:                        16:28:14   Distribution:                  chi2(3)
Cov. Estimator:                robust                                         
                                                                              
                             Parameter Estimates                              
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      89.090     2.6888     33.133     0.0000      83.820      94.360
tipuach       -0.4183     0.0337    -12.420     0.0000     -0.4843     -0.3523
cohsize        0.0798     0.0229     3.4856     0.0005      0.0349      0.1246
classize      -0.4749     0.1219    -3.8940     0.0001     -0.7139     -0.2359
==============================================================================

Endogenous: classize
Instruments: pred_class_size
Robust Covariance (Heteroskedastic)
Debiased: False</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the discontinuity-sample estimate
</div>
</div>
<div class="callout-body-container callout-body">
<p>Restricting the sample to cohorts near the enrollment cutoffs produces a larger negative estimate of the class-size effect. In the discontinuity sample, the coefficient on <code>classize</code> is <strong>-0.4749</strong>, which is roughly twice as large as the estimate in the full sample.</p>
<p>This is important because the discontinuity sample is closer to the spirit of a local fuzzy regression discontinuity design. By focusing on observations with cohort size in the ranges <span class="math inline">\([36,45]\)</span>, <span class="math inline">\([76,85]\)</span>, and <span class="math inline">\([116,125]\)</span>, the analysis places more weight on schools that are close to the thresholds where predicted class size jumps.</p>
<p>The larger coefficient suggests that the causal effect may be strongest in the local neighborhood around the cutoffs, which is exactly where the identifying variation is cleanest. At the same time, this estimate is less precise than the full-sample result, which is expected given the much smaller number of observations. Still, the sign and significance remain consistent with the paper’s main conclusion: <strong>smaller classes raise fifth-grade reading scores</strong>.</p>
</div>
</div>
</section>
<section id="cluster-standard-errors-at-the-school-level" class="level3">
<h3 class="anchored" data-anchor-id="cluster-standard-errors-at-the-school-level">Cluster standard errors at the school level</h3>
<p>The unit of observation in the replication is the class, but classes within the same school may share unobserved characteristics. This means that the residuals may be correlated within schools, which would make conventional heteroskedasticity-robust standard errors too small.</p>
<p>To address this, I cluster standard errors at the school level using <code>schlcode</code>. This follows the logic of the original paper, which adjusts inference for within-school correlation between classes. In practice, this affects precision more than point estimates, but it is important for making the replication comparable to the published results.</p>
<div id="1d37d966" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>iv_reading_clustered <span class="op">=</span> IV2SLS.from_formula(</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"avgverb ~ 1 + tipuach + cohsize + [classize ~ pred_class_size]"</span>,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    data<span class="op">=</span>g5</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>).fit(cov_type<span class="op">=</span><span class="st">"clustered"</span>, clusters<span class="op">=</span>g5[<span class="st">"schlcode"</span>])</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(iv_reading_clustered.summary)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                          IV-2SLS Estimation Summary                          
==============================================================================
Dep. Variable:                avgverb   R-squared:                      0.3084
Estimator:                    IV-2SLS   Adj. R-squared:                 0.3074
No. Observations:                2024   F-statistic:                    550.45
Date:                Tue, Apr 21 2026   P-value (F-stat)                0.0000
Time:                        16:28:14   Distribution:                  chi2(3)
Cov. Estimator:             clustered                                         
                                                                              
                             Parameter Estimates                              
==============================================================================
            Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
------------------------------------------------------------------------------
Intercept      84.942     1.4543     58.406     0.0000      82.092      87.793
tipuach       -0.3599     0.0161    -22.295     0.0000     -0.3915     -0.3282
cohsize        0.0206     0.0084     2.4663     0.0137      0.0042      0.0370
classize      -0.2321     0.0610    -3.8065     0.0001     -0.3516     -0.1126
==============================================================================

Endogenous: classize
Instruments: pred_class_size
Clustered Covariance (One-Way)
Debiased: False
Num Clusters: 1003</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the clustered-standard-error specification
</div>
</div>
<div class="callout-body-container callout-body">
<p>When I cluster standard errors at the school level, the estimated effect of class size on reading remains negative and statistically significant. The coefficient on <code>classize</code> is still <strong>-0.2321</strong>, while the standard error increases from about <strong>0.050</strong> to about <strong>0.061</strong>.</p>
<p>This is exactly what one would expect. Clustering changes the precision of the estimate, not the coefficient itself, because it adjusts for correlation in the error terms across classes within the same school. Since schools may share common resources, administrators, or student composition across classes, clustering is an appropriate correction in this setting.</p>
<p>The key takeaway is that the substantive result survives this more conservative inference procedure. Even after allowing for within-school dependence, the estimate remains statistically significant and economically meaningful. This makes the replication more comparable to the original paper, which also adjusts standard errors for within-school correlation.</p>
</div>
</div>
</section>
</section>
<section id="additional-analysis-visualizing-the-identification-strategy" class="level2">
<h2 class="anchored" data-anchor-id="additional-analysis-visualizing-the-identification-strategy">Additional Analysis: Visualizing the Identification Strategy</h2>
<p>As an additional exercise, I will supplement the regression results with a graphical representation of the paper’s identification strategy. Angrist and Lavy’s design relies on the fact that Maimonides’ rule creates discontinuous changes in predicted class size at enrollment thresholds of <span class="math inline">\(40\)</span>, <span class="math inline">\(80\)</span>, <span class="math inline">\(120\)</span>, and so on. If this rule is genuinely generating exogenous variation in class size, then the first-stage relationship should be visible in the data: observed class size should move with the nonlinear pattern implied by the rule.</p>
<p>I will plot cohort size against both actual class size and predicted class size from Maimonides’ rule. I will also plot average verbal scores against cohort size using binned averages. These figures make the causal logic of the paper easier to see. The first graph shows the treatment variation induced by the rule, while the second graph shows that achievement moves in a way consistent with smaller classes improving outcomes.</p>
<div id="fcf0f789" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-15-output-1.png" width="1119" height="640" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of full first-stage graph
</div>
</div>
<div class="callout-body-container callout-body">
<p>The full-sample graph shows the characteristic sawtooth pattern of the rule. More importantly, the observed average class size follows the same general shape, even though it does not match the rule perfectly. This visual evidence is consistent with the first-stage regression, where predicted class size strongly explains actual class size.</p>
</div>
</div>
<div id="298de270" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="hw2_questions_files/figure-html/cell-16-output-1.png" width="927" height="544" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Interpretation of the zoomed discontinuity graph
</div>
</div>
<div class="callout-body-container callout-body">
<p>The zoomed graph around the 40-student cutoff makes the identifying variation especially clear. As cohort size increases from 36 to 40, predicted class size rises from about 36 to 40 students. Once enrollment crosses from 40 to 41, predicted class size drops sharply to about 20.5 because the cohort is split into two classes:</p>
<p><span class="math display">\[
f_s = \frac{e_s}{\left\lfloor \frac{e_s - 1}{40} \right\rfloor + 1}.
\]</span></p>
<p>Observed class size also falls discretely at this cutoff, though not by exactly the same amount. This is why the design is best understood as a <strong>fuzzy regression discontinuity</strong>: the institutional rule creates a discontinuous change in expected class size, and actual class size responds strongly but not perfectly.</p>
</div>
</div>
<section id="why-this-strengthens-the-causal-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="why-this-strengthens-the-causal-interpretation">Why this strengthens the causal interpretation</h3>
<p>These graphs strengthen the causal interpretation of the paper’s estimates because they show that the source of variation is generated by an administrative rule rather than by ordinary differences across schools. Schools just below and just above a cutoff are likely to be similar in many ways, but they face different predicted class sizes because of the rule. The resulting discontinuity in actual class size is what allows the authors to isolate plausibly exogenous variation in treatment.</p>
<p>In this sense, the figures complement the 2SLS estimates by showing the logic of the design directly. The rule creates sharp nonlinearities in class size, and those nonlinearities provide the basis for causal inference.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Trevor Sullivan</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>